import type { Metadata } from "next";
import { Inter, Zen_Antique } from "next/font/google";
import "./globals.css";
import { PageContainer } from "@/features/common/components/PageContainer";

const inter = Inter({ subsets: ["latin"] });
const zenAntique = Zen_Antique({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
      <html lang="en">
        <body className={[inter.className, zenAntique.className].join(" ")}>
        <PageContainer>
        {children}
        </PageContainer>
        </body>
      </html>

);
}
